import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "./Pages.module.css";
import avatar from "../public/avatar.png";
import avatar1 from "../public/avatar1.jpg";
import avatar2 from "../public/avatar2.jpg";
import avatar3 from "../public/avatar3.webp";

const about = () => {
  return (
    <>
      <Head>
        <title>Codesware || About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.noCard}>
            
            <div className={styles.tags}>
              <h2>We are a Team of Workbench</h2>
              
              <small>Here is our Profiles</small>
              <hr />
            </div>
            <div className={styles.profiles}>
              <div className={styles.profileItems}>
                <div className={styles.profileImage}>
                <Image
                  src={avatar1}
                  width={150}
                  height={150}
                  alt="agatar"
                  className={styles.imgStyle}
                />
                </div>
                <br />
                <br />
                <hr />
                <div className={styles.aboutDest}>
                  <p>Name : Alian Walkar</p>
                  <p>Phone: 9864262488</p>
                  <p>Email: admin@walkar.com</p>
                  <p>Position: Founder & CEO</p>
                </div>
              </div>
              <div className={styles.profileItems}>
              <div className={styles.profileImage}>
                <Image
                  src={avatar2}
                  width={150}
                  height={150}
                  alt="agatar"
                  className={styles.imgStyle}
                />
                </div>
                <br />
                <br />
                <hr />
                <div className={styles.aboutDest}>
                  <p>Name : Alian Walkar</p>
                  <p>Phone: 9864262488</p>
                  <p>Email: info@walkar.com</p>
                  <p>Position: Manager</p>
                </div>
              </div>

              <div className={styles.profileItems}>
              <div className={styles.profileImage}>
                <Image
                  src={avatar3}
                  width={150}
                  height={150}
                  alt="agatar"
                  className={styles.imgStyle}
                />
                </div>
                <br />
                <br />
                <hr />
                <div className={styles.aboutDest}>
                  <p>Name : Alian Walkar</p>
                  <p>Phone: 9864262488</p>
                  <p>Email: service@walkar.com</p>
                  <p>Position: Marketing Officer</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default about;
