import React from "react";
import Head from "next/head";
import styles from "./Pages.module.css";

const contact = () => {
  return (
    <>
      <Head>
        <title>Codesware || Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <div className="grid">
          <h1>Place a Callback request</h1>
          <hr />
          <div className="card">
            <form action="/send-data-here" method="post">
              <div className={styles.formGroup}>
                <label htmlFor="name" className={styles.label}>
                  Name:
                </label>
                <br />
                <input
                  type="text"
                  id="name"
                  name="name"
                  className={styles.inputStyle}
                  placeholder="Alian Walker"
                />
              </div>

              <div className={styles.formGroup}>
                <label htmlFor="last" className={styles.label}>
                  Email:
                </label>
                <br />
                <input
                  type="text"
                  id="last"
                  name="last"
                  className={styles.inputStyle}
                  placeholder="walker@sample.com"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="last" className={styles.label}>
                  Phone Number:
                </label>
                <br />
                <input
                  type="number"
                  id="last"
                  name="last"
                  className={styles.inputStyle}
                  placeholder="9864000000"
                />
                <br />
                <small className={styles.red}>
                  (We will never share your contact details to anyone)
                </small>
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="first" className={styles.label}>
                  Your Query:
                </label>
                <br />
                <textarea
                  name="query"
                  id="query"
                  cols="21"
                  rows="5"
                  className={styles.inputStyle}
                  placeholder="Please Describe yor query"
                ></textarea>
              </div>
              <button type="submit" className={styles.contactBTN}>
                Submit
              </button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default contact;
