import React from "react";
import Head from "next/head";
import styles from "./Pages.module.css";
import Link from "next/link";

const login = () => {
  return (
    <>
      <Head>
        <title>Codesware || Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <div className="grid">
          <h1>Login To your Account</h1>
          <hr />
          <div className="card">
            <form action="/send-data-here" method="post">
              <div className={styles.formGroup}>
                <label htmlFor="last" className={styles.label}>
                  Email:
                </label>
                <br />
                <input
                  type="text"
                  id="last"
                  name="last"
                  className={styles.inputStyle}
                  placeholder="walker@sample.com"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="password" className={styles.label}>
                  Password:
                </label>
                <br />
                <input
                  type="password"
                  id="password"
                  name="password"
                  className={styles.inputStyle}
                  placeholder="****************"
                />
                <br />
                <br />
                <span className={styles.red}>

                  <b>
                    Do not have an account&nbsp;
                    <Link href="/register">
                      <u className={styles.pointer}>Click Here</u>
                    </Link>
                  </b>
                </span>
                <br />
                <br />
              </div>

              <button type="submit" className={styles.contactBTN}>
                Login
              </button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default login;
