import React from "react";
import Head from "next/head";
import styles from "./Pages.module.css";
import Link from "next/link";

const register = () => {
  return (
    <>
      <Head>
        <title>Codesware || Registration</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <div className="grid">
          <h1>Register Yourself</h1>
          <hr />
          <div className="card">
            <form action="/send-data-here" method="post">
              <div className={styles.formGroup}>
                <label htmlFor="last" className={styles.label}>
                  Name:
                </label>
                <br />
                <input
                  type="text"
                  id="last"
                  name="last"
                  className={styles.inputStyle}
                  placeholder="walker@sample.com"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="last" className={styles.label}>
                  Email:
                </label>
                <br />
                <input
                  type="text"
                  id="last"
                  name="last"
                  className={styles.inputStyle}
                  placeholder="walker@sample.com"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="password" className={styles.label}>
                  Password:
                </label>
                <br />
                <input
                  type="password"
                  id="password"
                  name="password"
                  className={styles.inputStyle}
                  placeholder="****************"
                />
              </div>
              <div className={styles.formGroup}>
                <label htmlFor="cpassword" className={styles.label}>
                  Confirm Password:
                </label>
                <br />
                <input
                  type="password"
                  id="cpassword"
                  name="cpassword"
                  className={styles.inputStyle}
                  placeholder="****************"
                />
              </div>
              <br />
              <span className={styles.red}>
                <b>
                  Already have an account&nbsp;
                  <Link href="/login">
                    <u className={styles.pointer}>Click Here</u>
                  </Link>
                </b>
              </span>
              <br />
              <br />
              <button type="submit" className={styles.contactBTN}>
                Register Me
              </button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default register;
